server:
  port: 8082

spring:
  application:
    name: search-service
  
  data:
    redis:
      host: localhost
      port: 6379
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=300s
    cache-names:
      - searchResults
      - tenantConfig

elasticsearch:
  host: localhost
  port: 9200

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    elasticsearch:
      enabled: true
    redis:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.enterprise.docsearch: DEBUG
    org.springframework.web: INFO
    co.elastic.clients: INFO
